var commandListJSON = '{"commands": [{'
				    + ' "variants": "move walk go north east south west n e s w",'
				    + ' "description": "allows you to move"'
    			+ '}, {'
			        + '"variants": "pickup get grab",'
			        + '"description": "allows you to pickup items"'
			    + '}, {'
			        + '"variants": "climb",'
			        + '"description": "climbs things"'
			    + '}, {'
			        + '"variants": "h help",'
			        + '"description": "displays help"'
			    + '}, {'
			        + '"variants": "i inv inventory",'
			        + '"description": "displays inventory"'
			    + '}, {'
			        + '"variants": "drop",'
			        + '"description": "drops items in current area"'
			    + '}, {'
			        + '"variants": "talk chat speak",'
			        + '"description": "talk npc allows you to start a conversation with a NPC"'
			    + '}, {'
			        + '"variants": "describe examine whatis",'
			        + '"description": "allows you to get more info on areas, items and npcs"'
			    + '}, {'
			        + '"variants": "map",'
			        + '"description": "allows you to see the map"'
			    + '}, {'
			        + '"variants": "setname",'
			        + '"description": "allows you to set your name"'
			    + '}, {'
			        + '"variants": "getname myname",'
			        + '"description": "displays your name"'
			    + '}, {'
			        + '"variants": "clr clear clearscreen clearterminal",'
			        + '"description": "clears the terminal window"'
			    + '}, {'
			        + '"variants": "fullscreen flscrn fullscrn",'
			        + '"description": "makes terminal fullscreen"'
			    + '}, {'
			        + '"variants": "zacisadick",'
			        + '"description": "magical command"'
    			+ '}]}';