var mapJSON = '{"area": [{'
    + '"title": "Large open field",'
    + '"description": "You are standing in a large open field, the grass is long and brushes your ankles. You can just about see the tips of small yellow flowers sticking out where they have been swamped by the unkept grass. To the north you can see a large building.",'
    + '"locked": 0,'
    + '"loc": { "x": 0, "y": 0 },'
    + '"exits": "east south",'
    + '"items": [{'
        + '"name": "knife",'
        + '"description": "An ordinary knife, the type you might use to cut your food at the dinner table.",'
        + '"weight": 1'
    + '}, {'
        + '"name": "fork",'
        + '"description": "An ordinary fork, the type you might use to stab your food at the dinner table.",'
        + '"weight": 1'
    + '}, {'
        + '"name": "spoon",'
        + '"description": "An ordinary spoon, the type you might use to eat your pudding at the dinner table.",'
        + '"weight": 1'
    + '}, {'
        + '"name": "spork",'
        + '"description": "An ordinary spork, you could eat ANYTHING with this",'
        + '"weight": 1'
    + '}],'
    + '"npcs": [{'
        + '"name": "John",'
        + '"description": "A burly man with faint aroma of coconut.",'
        + '"health": 100,'
        + '"exp": 9001,'
        + '"hostile": 1'
    + '}, {'
        + '"name": "Jane",'
        + '"description": "A dainty woman with a slight frame and bright smile.",'
        + '"health": 98,'
        + '"exp": 80085,'
        + '"hostile": 0'
    + '}]'
+ '}, {'
    + '"title": "Building entrance",'
    + '"description": "You are standing at the enterance of a large university building. Above the door is a large sign that reads \'The University of Portsmouth\'. It appears the door is open.",'
    + '"locked": 0,'
    + '"loc": { "x": 0, "y": 1 },'
    + '"exits": "north south",'
    + '"npcs": {'
        + '"name": "Bill",'
        + '"description": "A moustachioed gentleman with a fancy for scrambled eggs.",'
        + '"health": 50,'
        + '"exp": 1337,'
        + '"hostile": 0'
    + '}'
+ '}, {'
    + '"title": "Outside McDonald\'s",'
    + '"description": "It\'s surprising that the back alley is nicer than the actual restaurant...",'
    + '"locked": 0,'
    + '"loc": { "x": 2, "y": 1 },'
    + '"exits": "north"'
+ '}]'
+ '}';


